name: flutter_app_badger
description: Plugin to update the app badge on the launcher (both for Android and iOS)
version: 1.1.2
homepage: https://github.com/PROGrand/flutter_app_badger

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.mtbo.flutterappbadger
        pluginClass: FlutterAppBadgerPlugin
      ios:
        pluginClass: FlutterAppBadgerPlugin

environment:
  sdk: ">=2.9.0-14.1.beta <3.0.0"
  flutter: ">=1.19.0-4.3.pre <2.0.0"